                      -----DATA SEGMENTATION----
					---GROUPING PRODUCTS BASED ON  COST RANGE ------

WITH PRODUCT_SEGMENTS AS(
SELECT 
PRODUCT_KEY,
PRODUCT_NAME,
COST,
CASE WHEN COST<100 THEN 'BELOW 100'
     WHEN COST BETWEEN 100 AND 500 THEN '100-500'
	 WHEN COST BETWEEN 500 AND 1000 THEN '500-1000'
	 ELSE 'ABOVE 1000'
END COST_RANGE	 
FROM GOLD.DIM_PRODUCTS
)
SELECT
COST_RANGE,
COUNT(PRODUCT_KEY) AS TOTAL_PRODUCTS
FROM PRODUCT_SEGMENTS
GROUP BY COST_RANGE
ORDER BY TOTAL_PRODUCTS DESC


             -----GROUPING CUSTOMER BASED ON THEIR SPENDING BEHAVIOUR---------


WITH CUSTOMER_SPENDING AS (
SELECT 
C.CUSTOMER_KEY,
SUM(F.SALES_AMOUNT) AS TOTAL_SPENDING,
MIN(F.ORDER_DATE) AS FIRST_ORDER,
MAX(F.ORDER_DATE) AS LAST_ORDER,
(EXTRACT(YEAR FROM AGE(MAX(F.ORDER_DATE), MIN(F.ORDER_DATE))) * 12
 + EXTRACT(MONTH FROM AGE(MAX(F.ORDER_DATE), MIN(F.ORDER_DATE)))
) AS LIFESPAN
FROM GOLD.FACT_SALES F
LEFT JOIN GOLD.DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_KEY
)
SELECT
CUSTOMER_SEGMENT,
COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM(
SELECT
CUSTOMER_KEY,
TOTAL_SPENDING,
LIFESPAN,
CASE WHEN LIFESPAN >= 12 AND TOTAL_SPENDING>5000 THEN 'VIP'
     WHEN LIFESPAN >= 12 AND TOTAL_SPENDING <=5000 THEN 'REGULAR'
	 ELSE 'NEW'
END CUSTOMER_SEGMENT
FROM CUSTOMER_SPENDING) T
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_CUSTOMERS
