                     --PART TO WHOLE ANALYSIS--
							
								  
WITH CATEGORY_SALES AS(
SELECT 
CATEGORY,
SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM GOLD.FACT_SALES AS F
LEFT JOIN GOLD.DIM_PRODUCTS P 
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY CATEGORY
)
SELECT
CATEGORY,
TOTAL_SALES,
SUM(TOTAL_SALES)  OVER() OVERALL_SALES,
CONCAT(ROUND((TOTAL_SALES/SUM(TOTAL_SALES)  OVER())*100,2),'%') AS PERCENTAGE_OF_TOTAL_SALES
FROM CATEGORY_SALES
ORDER BY TOTAL_SALES DESC
