                                   ------BASE QUERY--------
WITH BASE_QUERY AS(
SELECT 
F.ORDER_NUMBER,
F.PRODUCT_KEY,
F.ORDER_DATE,
F.SALES_AMOUNT,
F.QUANTITY,
C.CUSTOMER_KEY,
C.CUSTOMER_NUMBER,
CONCAT(C.FIRST_NAME,' ' ,C.LAST_NAME) AS CUSTOMER_NAME,
C.BIRTHDATE,
EXTRACT(YEAR FROM AGE(CURRENT_DATE,C.BIRTHDATE)) AS AGE
FROM GOLD_FACT_SALES AS F
LEFT JOIN GOLD.DIM_CUSTOMERS AS C
ON C.CUSTOMER_KEY=F.CUSTOMER_KEY
WHERE ORDER_DATE IS NOT NULL
),
                         ---------CUSTOMER AGGREGATION----------
CUSTOMER_AGGREGATION AS(
SELECT 
CUSTOMER_KEY,
CUSTOMER_NUMBER,
CUSTOMER_NAME,
AGE,
COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
SUM(SALES_AMOUNT) AS TOTAL_SALES,
SUM(QUANTITY) AS TOTAL_QUANTITY,
COUNT(DISTINCT PRODUCT_KEY) AS TOTAL_PRODUCTS,
MAX(ORDER_DATE) AS LAST_ORDER_DATE,
(EXTRACT(YEAR FROM AGE(MAX(ORDER_DATE), MIN(ORDER_DATE))) * 12
 + EXTRACT(MONTH FROM AGE(MAX(ORDER_DATE), MIN(ORDER_DATE)))
) AS LIFESPAN
FROM BASE_QUERY
GROUP BY 
CUSTOMER_KEY,
CUSTOMER_NUMBER,
CUSTOMER_NAME,
AGE)
       -------FINAL QUERY-----
SELECT
CUSTOMER_KEY,
CUSTOMER_NUMBER,
CUSTOMER_NAME,
TOTAL_ORDERS,
LAST_ORDER_DATE,
TOTAL_QUANTITY,
TOTAL_PRODUCTS,
TOTAL_QUANTITY,
TOTAL_PRODUCTS,
TOTAL_SALES,
LIFESPAN,
AGE,
CASE WHEN AGE< 20 THEN 'UNDER 20'
     WHEN AGE BETWEEN 20 AND 29 THEN '20-29'
	 WHEN AGE BETWEEN 30 AND 29 THEN '30-39'
	 WHEN AGE BETWEEN 40 AND 29 THEN '40-49'
	 ELSE '50 AND ABOVE'
END AS AGE_GROUP,	

CASE WHEN LIFESPAN >= 12 AND TOTAL_SALES>5000 THEN 'VIP'
     WHEN LIFESPAN >= 12 AND TOTAL_SALES <=5000 THEN 'REGULAR'
	 ELSE 'NEW'
END CUSTOMER_SEGMENT,

EXTRACT(YEAR FROM AGE(CURRENT_DATE,LAST_ORDER_DATE)) * 12 
+ EXTRACT(MONTH FROM AGE(CURRENT_DATE,LAST_ORDER_DATE))AS RECENCY,
----COMPUTE AVEARGE ORDER---
CASE WHEN TOTAL_ORDERS=0 THEN 0
     ELSE TOTAL_SALES/TOTAL_ORDERS 
	 END AS AVG_ORDER_VALUE,
	 ------- COMPUTE AVEAGE MONTHLY SPEND -----------
CASE WHEN LIFESPAN= 0 THEN TOTAL_SALES
     ELSE TOTAL_SALES/LIFESPAN
	 END AS AVG_MONTHLY_SALES
FROM CUSTOMER_AGGREGATION
