                    -------------------PERFORMANCE ANALYSIS---------------

					  
WITH YEARLY_PRODUCT_SALES AS(
SELECT 
EXTRACT(YEAR FROM F.ORDER_DATE) AS ORDER_YEAR,
SUM(F.SALES_AMOUNT) AS CURRENT_SALES,
P.PRODUCT_NAME
FROM GOLD.FACT_SALES AS F
LEFT JOIN GOLD.DIM_PRODUCTS P 
ON F.PRODUCT_KEY = P.PRODUCT_KEY
WHERE F.ORDER_DATE IS NOT NULL
GROUP BY 
EXTRACT(YEAR FROM F.ORDER_DATE),
P.PRODUCT_NAME
)
SELECT ORDER_YEAR,
PRODUCT_NAME,
CURRENT_SALES,
ROUND(AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME)) AS AVG_SALES,
CURRENT_SALES - ROUND(AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME)) AS DIFF_AVG,

                ---PRODUCT PERFOMANCE ANALYSIS--------
CASE WHEN CURRENT_SALES - ROUND(AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME)) > 0 THEN 'ABOVE AVERAGE'
     WHEN CURRENT_SALES - ROUND(AVG(CURRENT_SALES) OVER(PARTITION BY PRODUCT_NAME)) < 0 THEN 'BELOW AVEARGE'
	 ELSE 'AVEREGE'
END AVG_CHANGE	, 

             -----YEAR OVER YEAR ANALYSIS
LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) PY_SALES,
CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR)AS  DIFF_PY,

CASE WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
     WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
	 ELSE 'NO CHANGE'
END PY_CHANGE
FROM YEARLY_PRODUCT_SALES
ORDER BY PRODUCT_NAME,ORDER_YEAR

